/**
 * Quick-fill templates for the poll finalize step. The `{details}` placeholder
 * is filled at send time: with the auto-generated conference URL when the
 * calendar write created one (e.g. Google Meet / Teams), otherwise with nothing -
 * hosts replace it with their own Zoom link, phone number or address in the
 * textarea before confirming. Pure module: safe to import from client + server.
 */

export const FINALIZE_MESSAGE_PLACEHOLDER = "{details}";

export interface FinalizeMessageTemplate {
  value: string;
  label: string;
  text: string;
}

/** A named, reusable meeting-details message the host saved for polls. */
export interface PollMessageTemplate {
  id: string;
  name: string;
  body: string;
  isDefault: boolean;
}

export const POLL_TEMPLATE_NAME_MAX = 60;
export const POLL_TEMPLATE_BODY_MAX = 2000;

/** Validate a template's name/body; returns a user-facing error string, or null. */
export function validatePollTemplate(input: {
  name: string;
  body: string;
}): string | null {
  const name = input.name.trim();
  const body = input.body.trim();
  if (!name) return "Give the template a name.";
  if (name.length > POLL_TEMPLATE_NAME_MAX) {
    return `Template names are at most ${POLL_TEMPLATE_NAME_MAX} characters.`;
  }
  if (!body) return "Add the message text for the template.";
  if (body.length > POLL_TEMPLATE_BODY_MAX) {
    return `Templates are at most ${POLL_TEMPLATE_BODY_MAX} characters.`;
  }
  return null;
}

export const FINALIZE_MESSAGE_TEMPLATES: FinalizeMessageTemplate[] = [
  {
    value: "video",
    label: "Video call",
    text: `We'll meet over video.\n\nJoin here: ${FINALIZE_MESSAGE_PLACEHOLDER}`,
  },
  {
    value: "phone",
    label: "Phone call",
    text: `We'll connect by phone.\n\nDial-in number: ${FINALIZE_MESSAGE_PLACEHOLDER}`,
  },
  {
    value: "in_person",
    label: "In person",
    text: `We'll meet in person.\n\nAddress: ${FINALIZE_MESSAGE_PLACEHOLDER}`,
  },
];

/** Fill the `{details}` placeholder in a finalize message with the generated
 * meeting URL when one exists; otherwise leave the text as the host wrote it
 * (they can paste their own link instead of the placeholder). */
export function applyFinalizeMessage(
  message: string | null | undefined,
  meetingUrl: string | undefined,
): string | undefined {
  const trimmed = message?.trim();
  if (!trimmed) return undefined;
  if (meetingUrl) return trimmed.replaceAll(FINALIZE_MESSAGE_PLACEHOLDER, meetingUrl);
  return trimmed;
}

/** Fill the `{details}` placeholder for a calendar-event description, where the
 * provider's own conference link isn't known yet (it's generated by the write).
 * Falls back to the human-readable location label so no raw placeholder leaks
 * into the provider's invite. */
export function applyCalendarMessage(
  message: string | null | undefined,
  locationLabel: string | undefined,
): string | undefined {
  const trimmed = message?.trim();
  if (!trimmed) return undefined;
  return trimmed.replaceAll(FINALIZE_MESSAGE_PLACEHOLDER, locationLabel ?? "");
}
